/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gaze;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author C. Levallois
 */
public class Screen_1 extends javax.swing.JFrame {
    private String workingDirectory;
    private boolean fileSelected;
    private String fileSelectedPathANdName;
    private String fileSelectedName;
    public static Screen_1 screen_1;
    public static Screen_2 screen_2;
    public static Screen_3 screen_3;
    File f;
    /**
     * Creates new form Screen_1
     */
    public Screen_1() throws IOException {
        initComponents();
        findStructureButton.setEnabled(false);
        f = new File(new File(".").getCanonicalPath());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectFileButton = new javax.swing.JButton();
        findStructureButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        creditsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        jLabel1.setText("Gaze");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel2.setText("find structure in your network");

        selectFileButton.setText("select file");
        selectFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileButtonActionPerformed(evt);
            }
        });

        findStructureButton.setText("find structure!");
        findStructureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findStructureButtonActionPerformed(evt);
            }
        });

        jButton3.setText("under the hood");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        result.setText("<html><b>Done!</b><br><br>2 files have been created:<br>- a list of nodes<br>- a list of edges<br><br>These files are in the same folder as your original file.<br>You can import these files into Gephi or any other network viz software to explore the structure of your network.</html>");

        creditsButton.setText("credits");
        creditsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(creditsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(selectFileButton)
                                .addGap(64, 64, 64)
                                .addComponent(findStructureButton)))
                        .addContainerGap(72, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectFileButton)
                    .addComponent(findStructureButton))
                .addGap(36, 36, 36)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(creditsButton))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileButtonActionPerformed
        if (evt.getSource() == selectFileButton) {
            System.out.println("selectFileButton clicked");


        }
        JFileChooser chooser = new JFileChooser();

        chooser.setCurrentDirectory(f);
        //chooser.setCurrentDirectory(new java.io.File("D:\\Docs Pro Clement\\E-humanities\\TextMining\\Exported Items\\"));
        chooser.setDialogTitle("Select a file");
        //chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            System.out.println("Current directory: " + chooser.getCurrentDirectory().getAbsolutePath());
            
            workingDirectory = chooser.getCurrentDirectory().getAbsolutePath().toString();
            fileSelected = true;
            fileSelectedPathANdName = chooser.getSelectedFile().toString();
            fileSelectedName = chooser.getSelectedFile().getName();
            System.out.println("Selected File: " + fileSelectedPathANdName);
            findStructureButton.setEnabled(true);
        } else {
            System.out.println("No Selection");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_selectFileButtonActionPerformed

    private void findStructureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findStructureButtonActionPerformed
        if (evt.getSource() == findStructureButton) {


            if (fileSelected) {

                //System.out.println(String.valueOf(countHTML));
                String[] args;
                args = new String[9];
                args[0] = workingDirectory;
                args[1] = fileSelectedPathANdName;
                args[2] = fileSelectedName;
                args[3] = new Boolean(screen_2.directedNetwork.isSelected()).toString();
                args[4] = new Boolean(screen_2.weightNetwork.isSelected()).toString();
                System.out.println(args[3]);
                try {
//                args[4] = Screen2.maxWordsField.getText();          
                args[5] = screen_2.cosineMin.getText();
                args[6] = screen_2.maxTargets4Calc.getText();
                args[7] = screen_2.minOccAsTarget.getText();
                args[8] = screen_2.minOccAsSource.getText();
//                args[8] = Screen2.fileSelectedPathANdName;
//                args[9] = new Boolean(Screen2.deleteChars.isSelected()).toString();
                //logArea.append(workingDirectory);
                //                    args[1] = String.valueOf(countPDF);
            } catch (NullPointerException e){System.out.println("this value should not be null");}
      
                Runnable r = new Controller(args[0],args[2],args[3],args[4],args[5],args[6],args[7],args[8]);
                new Thread(r).start();


            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_findStructureButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        screen_2.setVisible(true);
        screen_1.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void creditsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsButtonActionPerformed
        screen_3.setVisible(true);
        screen_1.setVisible(false);
    }//GEN-LAST:event_creditsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {


            public void run() {
                try {
                    screen_1 = new Screen_1();
                    screen_1.result.setVisible(false);
                    screen_1.setVisible(true);
                    screen_2 = new Screen_2();
                    screen_2.setVisible(false);
                    screen_3 = new Screen_3();
                    screen_3.setVisible(false);
                } catch (IOException ex) {
                    Logger.getLogger(Screen_1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creditsButton;
    private javax.swing.JButton findStructureButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel result;
    private javax.swing.JButton selectFileButton;
    // End of variables declaration//GEN-END:variables
}
